### ISSUE TITLE
HTML field (redactor) strips out commas from "tel:" links

### ISSUE THREAD

**Issue by danbrellis** [craftcms/html-field#12]
### Description
When saving a redactor field with a phone number that contains commas (`,`) it is parsed to remove those commas. This is problematic for conference call-in numbers that use the commas to 'pause' before dialing the dial-in passcode. This is ultimately a result of HTML Purifier and I have opened an issue with them: https://github.com/ezyang/htmlpurifier/issues/388

However, just like Craft will sanitize svgs before running the purifier and then putting them back, I wonder if this is something Craft should handle?

See https://github.com/craftcms/html-field/blob/main/src/HtmlField.php#L198-L213

Alternatively, I would think a BEFORE_PURIFY and AFTER_PURIFY event pair would be practical here so I could santize those links myself. Other ideas or guidance is apperciated.

### Steps to reproduce

1. Create a redactor field with 'purify html' enabled.
2. Create a hyperlink with the href of `tel:+12029910477,,32288696#`
3. Save and see how the href is now `tel:+1202991047732288696#` (no commas)

### Additional info

- Craft version: Pro 4.5.6.1
- PHP version: 8.1
- Plugins & versions: craftcms/redactor (v3.0.4)

**Comment by brandonkelly** [comment]
Looks like this ended up getting resolved in HTML Purifier 4.17.0 via your PR https://github.com/ezyang/htmlpurifier/pull/389 🎉
