### ISSUE TITLE
`valueType()` should be more than `string`

### ISSUE THREAD

**Issue by markhuot** [craftcms/html-field#13]
https://github.com/craftcms/html-field/blob/4797c9cb0397e6d69d25d9716a75f7b47c69fd3a/src/HtmlField.php#L40

At the very least this should probably be `string|null`. But it would be really nice to see the `HtmlFieldData|null` in there…?

**Comment by brandonkelly** [comment]
Just tagged v2.1.1 and 3.1.1 with that change.
